const ENTRY_TYPES=["traits","actions","reactions","legendary","lair","regional"];const abilityOrder=["str","dex","con","int","wis","cha"];const entryState={traits:[],actions:[],reactions:[],legendary:[],lair:[],regional:[]};let skillEntries=[];let uploadedArtData="";
document.addEventListener("DOMContentLoaded",()=>{populateSelect("size",DATA.sizes);populateSelect("type",DATA.types);populateSelect("alignment",DATA.alignments);populateCR();buildTags("resistances",DATA.damageTypes);buildTags("immunities",DATA.damageTypes);buildTags("vulnerabilities",DATA.damageTypes);buildTags("conditionImmunities",DATA.conditions);addEntry("traits",{name:"Острое зрение",text:"Монстр совершает проверки Мудрости (Восприятие), основанные на зрении, с преимуществом."});addEntry("actions",{name:"Укус",text:"Атака оружием ближнего боя: +3 к попаданию, досягаемость 5 фт., одна цель. Попадание: 5 (1к6 + 2) колющего урона."});addSkill({skillId:"perception",prof:1});document.querySelectorAll("input,select,textarea").forEach(el=>{el.addEventListener("input",updateAll);el.addEventListener("change",updateAll);if(el.tagName==="TEXTAREA")attachAutoGrow(el)});document.getElementById("jsonLoader").addEventListener("change",handleJSONLoad);document.getElementById("imageUpload").addEventListener("change",handleImageUpload);document.querySelectorAll(".help-btn").forEach(btn=>btn.addEventListener("click",()=>openHelp(btn.dataset.helpTitle||"Подсказка",btn.dataset.helpText||"",btn.dataset.helpImage||"")));document.getElementById("helpModal").addEventListener("click",e=>{if(e.target.id==="helpModal")closeHelp()});updateAll()});
function attachAutoGrow(el){const resize=()=>{el.style.height="auto";el.style.height=Math.max(el.scrollHeight,120)+"px"};el.addEventListener("input",resize);setTimeout(resize,0)}
function populateSelect(id,values){const el=document.getElementById(id);values.forEach(v=>{const o=document.createElement("option");o.value=v;o.textContent=v;el.appendChild(o)})}
function populateCR(){const el=document.getElementById("cr");DATA.crTable.forEach(r=>{const o=document.createElement("option");o.value=r.cr;o.textContent=`${r.cr} (${r.xp.toLocaleString("ru-RU")} XP)`;el.appendChild(o)});el.value="1/2"}
function openHelp(title,text,image){document.getElementById("helpTitle").textContent=title;document.getElementById("helpText").textContent=text;const img=document.getElementById("helpImage");if(image){img.src=image;img.hidden=false}else{img.hidden=true;img.removeAttribute("src")}document.getElementById("helpModal").hidden=false}
function closeHelp(){document.getElementById("helpModal").hidden=true}
function buildTags(id,items){const root=document.getElementById(id);items.forEach(item=>{const label=document.createElement("label");label.className="tag";label.innerHTML=`<input type="checkbox" value="${item}"><span>${item}</span>`;const input=label.querySelector("input");input.addEventListener("change",()=>{label.classList.toggle("active",input.checked);updateAll()});root.appendChild(label)})}
function uid(){return crypto.randomUUID?crypto.randomUUID():String(Date.now()+Math.random())}
function addEntry(type,defaults={}){entryState[type].push({id:uid(),name:defaults.name||"",text:defaults.text||""});renderEntries(type);updateAll()}
function removeEntry(type,id){entryState[type]=entryState[type].filter(x=>x.id!==id);renderEntries(type);updateAll()}
function renderEntries(type){const map={traits:"traitsEditor",actions:"actionsEditor",reactions:"reactionsEditor",legendary:"legendaryEditor",lair:"lairEditor",regional:"regionalEditor"};const root=document.getElementById(map[type]);root.innerHTML="";entryState[type].forEach(item=>{const card=document.createElement("div");card.className="entry-card";card.innerHTML=`<div class="entry-top"><input type="text" placeholder="Название" value="${escapeAttr(item.name)}"><button type="button" class="secondary">Удалить</button></div><textarea rows="4" class="auto-grow" placeholder="Описание">${escapeHtml(item.text)}</textarea>`;const [nameInput,removeBtn]=card.querySelectorAll(".entry-top > *");const textarea=card.querySelector("textarea");attachAutoGrow(textarea);nameInput.addEventListener("input",e=>{item.name=e.target.value;updateAll()});textarea.addEventListener("input",e=>{item.text=e.target.value;updateAll()});removeBtn.addEventListener("click",()=>removeEntry(type,item.id));root.appendChild(card)})}
function addSkill(defaults={}){skillEntries.push({id:uid(),skillId:defaults.skillId||DATA.skills[0].id,prof:defaults.prof||1});renderSkills();updateAll()}
function removeSkill(id){skillEntries=skillEntries.filter(x=>x.id!==id);renderSkills();updateAll()}
function renderSkills(){const root=document.getElementById("skillEntries");root.innerHTML="";skillEntries.forEach(item=>{const card=document.createElement("div");card.className="entry-card";const options=DATA.skills.map(skill=>`<option value="${skill.id}" ${skill.id===item.skillId?"selected":""}>${skill.label}</option>`).join("");card.innerHTML=`<div class="skill-entry-title">Навык</div><div class="skill-entry-top"><select>${options}</select><select><option value="1" ${item.prof===1?"selected":""}>проф.</option><option value="2" ${item.prof===2?"selected":""}>эксп.</option></select><button type="button" class="secondary">Удалить</button></div>`;const selects=card.querySelectorAll("select");selects[0].addEventListener("change",e=>{item.skillId=e.target.value;updateAll()});selects[1].addEventListener("change",e=>{item.prof=Number(e.target.value);updateAll()});card.querySelector("button").addEventListener("click",()=>removeSkill(item.id));root.appendChild(card)})}
function num(id){const el=document.getElementById(id);return Number((el&&el.value)||0)}function text(id){const el=document.getElementById(id);return String((el&&el.value)||"").trim()}function mod(score){return Math.floor((score-10)/2)}function fmtSigned(n){return`${n>=0?"+":""}${n}`}function formatAbility(score){return`${score} (${fmtSigned(mod(score))})`}function checkedValues(rootId){return Array.from(document.querySelectorAll(`#${rootId} input[type="checkbox"]:checked`)).map(el=>el.value)}function getCRRow(cr){return DATA.crTable.find(x=>x.cr===cr)||DATA.crTable[0]}function getCurrentPB(){return getCRRow(text("cr")).pb}
function buildTypeLine(){const size=text("size"),type=text("type"),subtype=text("subtype"),alignment=text("alignment");const core=subtype?`${size}, ${type} (${subtype})`:`${size}, ${type}`;return`${core}, ${alignment}`}
function buildSpeedLine(){const parts=[];[["speedWalk",""],["speedBurrow","рытьё"],["speedClimb","лазание"],["speedFly","полет"],["speedSwim","плавание"]].forEach(([id,label])=>{const v=num(id);if(v>0)parts.push(label?`${label} ${v} фт.`:`${v} фт.`)});const special=text("speedSpecial");if(special)parts.push(special);return parts.length?parts.join(", "):"—"}
function autoHitDiceExpression(size,hp,conScore){const die=DATA.hitDieBySize[size]||8;const avgDie={4:2.5,6:3.5,8:4.5,10:5.5,12:6.5,20:10.5}[die]||4.5;const conMod=mod(conScore);const perDie=Math.max(1,avgDie+conMod);const diceCount=Math.max(1,Math.round(hp/perDie));const bonus=diceCount*conMod;return bonus===0?`${diceCount}к${die}`:`${diceCount}к${die} ${bonus>0?"+":"-"} ${Math.abs(bonus)}`}
function getScores(){return{str:num("str"),dex:num("dex"),con:num("con"),int:num("int"),wis:num("wis"),cha:num("cha")}}
function buildSaves(scores,pb){const labels={saveStr:"Сил",saveDex:"Лов",saveCon:"Тел",saveInt:"Инт",saveWis:"Мдр",saveCha:"Хар"};const map={saveStr:"str",saveDex:"dex",saveCon:"con",saveInt:"int",saveWis:"wis",saveCha:"cha"};const out=[];Object.keys(labels).forEach(id=>{if(document.getElementById(id).checked)out.push(`${labels[id]} ${fmtSigned(mod(scores[map[id]])+pb)}`)});return out}
function buildSkillsLine(scores,pb){return skillEntries.map(entry=>{const skill=DATA.skills.find(s=>s.id===entry.skillId);const bonus=mod(scores[skill.ability])+pb*Number(entry.prof);return`${skill.label} ${fmtSigned(bonus)}`})}
function buildSensesLine(){const parts=[];[["senseBlindsight","слепое зрение"],["senseDarkvision","тёмное зрение"],["senseTremorsense","чувство вибрации"],["senseTruesight","истинное зрение"]].forEach(([id,label])=>{const v=num(id);if(v>0)parts.push(`${label} ${v} фт.`)});parts.push(`пассивное Восприятие ${num("passivePerception")}`);return parts.join(", ")}
function renderFact(id,label,values){const el=document.getElementById(id);if(!values||(Array.isArray(values)&&values.length===0)){el.textContent="";return}const content=Array.isArray(values)?values.join(", "):values;el.innerHTML=`<strong>${label}</strong> ${escapeHtml(content)}`}
function renderEntriesOut(id,items){const root=document.getElementById(id);root.innerHTML="";const filled=items.filter(item=>item.name.trim()||item.text.trim());filled.forEach(item=>{const p=document.createElement("p");p.className="entry-render";const name=item.name.trim()?`<em>${escapeHtml(item.name)}.</em> `:"";p.innerHTML=`${name}${escapeHtml(item.text).replace(/\n/g,"<br>")}`;root.appendChild(p)});root.parentElement.style.display=filled.length?"":"none"}
function estimateCRByHP(hp){return DATA.crTable.find(r=>hp>=r.hpMin&&hp<=r.hpMax)||(hp>850?DATA.crTable[DATA.crTable.length-1]:DATA.crTable[0])}
function estimateCRByDPR(dpr){return DATA.crTable.find(r=>dpr>=r.dprMin&&dpr<=r.dprMax)||(dpr>320?DATA.crTable[DATA.crTable.length-1]:DATA.crTable[0])}
function crToIndex(cr){return DATA.crTable.findIndex(r=>r.cr===cr)}function indexToCR(idx){const bounded=Math.max(0,Math.min(DATA.crTable.length-1,idx));return DATA.crTable[bounded]}
function estimateBalancedCR(){const hp=num("hp"),ac=num("ac"),dpr=num("dpr"),atk=num("attackBonus"),dc=num("saveDc");let def=estimateCRByHP(hp);def=indexToCR(crToIndex(def.cr)+Math.round((ac-def.ac)/2));let off=estimateCRByDPR(dpr);off=indexToCR(crToIndex(off.cr)+Math.round(Math.max(atk-off.atk,dc-off.dc)/2));return{defensive:def,offensive:off,final:indexToCR(Math.round((crToIndex(def.cr)+crToIndex(off.cr))/2))}}
function validate(scores,pb,estimated){const warnings=[];const selectedCR=getCRRow(text("cr"));const ac=num("ac"),hp=num("hp"),dpr=num("dpr"),atk=num("attackBonus"),dc=num("saveDc");const passiveExpected=10+mod(scores.wis)+skillEntries.filter(x=>x.skillId==="perception").reduce((acc,x)=>acc+pb*Number(x.prof),0);if(num("passivePerception")!==passiveExpected)warnings.push({level:"warn",text:`Пассивное Восприятие сейчас ${num("passivePerception")}, а по выбранным параметрам ожидается ${passiveExpected}.`});const gap=Math.abs(crToIndex(selectedCR.cr)-crToIndex(estimated.final.cr));if(gap>=4)warnings.push({level:"bad",text:`Выбранный CR (${selectedCR.cr}) сильно расходится с грубой оценкой по DMG (${estimated.final.cr}).`});else if(gap>=2)warnings.push({level:"warn",text:`Выбранный CR (${selectedCR.cr}) отличается от грубой оценки (${estimated.final.cr}).`});else warnings.push({level:"good",text:`CR выглядит близким к черновой оценке баланса (${estimated.final.cr}).`});if(ac-selectedCR.ac>=3)warnings.push({level:"warn",text:`КД заметно выше типичного для CR ${selectedCR.cr}.`});if(hp>selectedCR.hpMax+30)warnings.push({level:"warn",text:`Хитов больше типичного диапазона для CR ${selectedCR.cr}.`});if(dpr>selectedCR.dprMax+10)warnings.push({level:"warn",text:`Средний урон за раунд выше типичного для CR ${selectedCR.cr}.`});if(atk>selectedCR.atk+3)warnings.push({level:"warn",text:`Бонус атаки заметно выше типичного для CR ${selectedCR.cr}.`});if(dc>selectedCR.dc+2)warnings.push({level:"warn",text:`Сложность спасброска заметно выше типичной для CR ${selectedCR.cr}.`});const note=text("balanceNote");if(note)warnings.push({level:"good",text:`Учтено примечание: ${note}`});return warnings}
function renderWarnings(items){const root=document.getElementById("warnings");root.innerHTML="";items.forEach(item=>{const div=document.createElement("div");div.className=`warning ${item.level}`;div.textContent=item.text;root.appendChild(div)})}
function updateLayoutMode(){const mode=text("layoutMode");const hasArt=Boolean(uploadedArtData);const hasDesc=Boolean(text("description")||text("calloutText"));const root=document.getElementById("previewCanvas");root.classList.remove("mode-showcase","mode-statblock");const useShowcase=mode==="showcase";root.classList.add(useShowcase?"mode-showcase":"mode-statblock");document.getElementById("showcaseTop").style.display=useShowcase?"grid":"none";const img=document.getElementById("monsterArt");if(uploadedArtData)img.src=uploadedArtData;else img.removeAttribute("src");document.querySelector(".showcase-art").style.display=(uploadedArtData||useShowcase)?"block":"none"}
function updateShowcase(){document.getElementById("showcaseTitle").textContent=text("name")||"Описание";document.getElementById("showcaseDescription").innerHTML=(text("description")||"Добавь описание сущности, её повадки, происхождение или заметки для мастера.").replace(/&/g,"&amp;").replace(/</g,"&lt;").replace(/>/g,"&gt;").replace(/\n/g,"<br>");const callout=text("calloutText");document.getElementById("showcaseCallout").innerHTML=escapeHtml(callout).replace(/\n/g,"<br>");document.getElementById("calloutBox").style.display=callout?"":"none"}
function updateAll(){const scores=getScores(),pb=getCurrentPB();if(document.getElementById("autoHitDice").checked){document.getElementById("hitDice").value=autoHitDiceExpression(text("size"),num("hp"),scores.con)}["str","dex","con","int","wis","cha"].forEach(key=>document.getElementById(`${key}Mod`).textContent=fmtSigned(mod(scores[key])));document.getElementById("outName").textContent=text("name")||"Монстр";document.getElementById("outTypeLine").textContent=buildTypeLine();document.getElementById("outAC").textContent=num("ac");document.getElementById("outHP").textContent=text("hitDice")?`${num("hp")} (${text("hitDice")})`:`${num("hp")}`;document.getElementById("outSpeed").textContent=buildSpeedLine();document.getElementById("abilityRow").innerHTML=abilityOrder.map(key=>`<td>${formatAbility(scores[key])}</td>`).join("");renderFact("outSaves","Спасброски",buildSaves(scores,pb));renderFact("outSkills","Навыки",buildSkillsLine(scores,pb));renderFact("outVuln","Уязвимости к урону",checkedValues("vulnerabilities"));renderFact("outRes","Сопротивления урону",checkedValues("resistances"));renderFact("outImm","Иммунитеты к урону",checkedValues("immunities"));renderFact("outCondImm","Иммунитеты к состояниям",checkedValues("conditionImmunities"));renderFact("outSenses","Чувства",buildSensesLine());renderFact("outLanguages","Языки",text("languages")||"—");const crRow=getCRRow(text("cr"));renderFact("outCR","Опасность",`${crRow.cr} (${crRow.xp.toLocaleString("ru-RU")} XP), бонус мастерства ${fmtSigned(crRow.pb)}`);renderEntriesOut("outTraits",entryState.traits);renderEntriesOut("outActions",entryState.actions);renderEntriesOut("outReactions",entryState.reactions);renderEntriesOut("outLegendary",entryState.legendary);renderEntriesOut("outLair",entryState.lair);renderEntriesOut("outRegional",entryState.regional);const legendaryDescription=text("legendaryDescription");document.getElementById("outLegendaryDescription").innerHTML=escapeHtml(legendaryDescription).replace(/\n/g,"<br>");document.getElementById("legendarySection").style.display=(entryState.legendary.some(x=>x.name.trim()||x.text.trim())||legendaryDescription)?"":"none";const estimated=estimateBalancedCR();document.getElementById("balanceChip").textContent=`CR ≈ ${estimated.final.cr}`;renderWarnings(validate(scores,pb,estimated));updateShowcase();updateLayoutMode()}
function handleImageUpload(event){const file=event.target.files[0];if(!file)return;const reader=new FileReader();reader.onload=e=>{uploadedArtData=e.target.result;updateAll()};reader.readAsDataURL(file)}
function collectState(){const ids=["name","size","type","subtype","alignment","cr","ac","hp","hitDice","autoHitDice","speedWalk","speedClimb","speedSwim","speedFly","speedBurrow","speedSpecial","str","dex","con","int","wis","cha","saveStr","saveDex","saveCon","saveInt","saveWis","saveCha","senseBlindsight","senseDarkvision","senseTremorsense","senseTruesight","passivePerception","languages","dpr","attackBonus","saveDc","balanceNote","legendaryDescription","layoutMode","description","calloutText"];const state={fields:{},tags:{},entries:entryState,skillEntries,art:uploadedArtData};ids.forEach(id=>{const el=document.getElementById(id);state.fields[id]=el.type==="checkbox"?el.checked:el.value});["resistances","immunities","vulnerabilities","conditionImmunities"].forEach(key=>state.tags[key]=checkedValues(key));return state}
function applyState(state){Object.entries(state.fields||{}).forEach(([id,value])=>{const el=document.getElementById(id);if(!el)return;if(el.type==="checkbox")el.checked=Boolean(value);else el.value=value});uploadedArtData=state.art||"";["resistances","immunities","vulnerabilities","conditionImmunities"].forEach(key=>{Array.from(document.querySelectorAll(`#${key} input[type="checkbox"]`)).forEach(input=>{input.checked=(state.tags?.[key]||[]).includes(input.value);input.parentElement.classList.toggle("active",input.checked)})});skillEntries=Array.isArray(state.skillEntries)?state.skillEntries:[];renderSkills();ENTRY_TYPES.forEach(type=>{entryState[type]=Array.isArray(state.entries?.[type])?state.entries[type]:[];renderEntries(type)});updateAll()}
function downloadJSON(){const blob=new Blob([JSON.stringify(collectState(),null,2)],{type:"application/json;charset=utf-8"});triggerDownload(blob,`${slugify(text("name")||"monster")}.json`)}
function loadJSON(){document.getElementById("jsonLoader").click()}
function handleJSONLoad(event){const file=event.target.files[0];if(!file)return;const reader=new FileReader();reader.onload=e=>{try{applyState(JSON.parse(e.target.result))}catch(err){alert("Не удалось прочитать JSON. Проверь файл.");console.error(err)}};reader.readAsText(file,"utf-8");event.target.value=""}
function downloadPNG(){updateAll();const node=document.getElementById("previewCanvas");const clone=node.cloneNode(true);const wrapper=document.createElement("div");wrapper.setAttribute("xmlns","http://www.w3.org/1999/xhtml");wrapper.appendChild(clone);const styleText=Array.from(document.styleSheets).map(sheet=>{try{return Array.from(sheet.cssRules).map(rule=>rule.cssText).join("\n")}catch(e){return""}}).join("\n");const svg=`<svg xmlns="http://www.w3.org/2000/svg" width="${node.offsetWidth}" height="${node.offsetHeight}"><foreignObject width="100%" height="100%"><div xmlns="http://www.w3.org/1999/xhtml"><style>${styleText}</style>${wrapper.innerHTML}</div></foreignObject></svg>`;const img=new Image();const url=URL.createObjectURL(new Blob([svg],{type:"image/svg+xml;charset=utf-8"}));img.onload=()=>{const canvas=document.createElement("canvas");canvas.width=node.offsetWidth*2;canvas.height=node.offsetHeight*2;const ctx=canvas.getContext("2d");ctx.scale(2,2);ctx.fillStyle="#efe7d4";ctx.fillRect(0,0,node.offsetWidth,node.offsetHeight);ctx.drawImage(img,0,0);canvas.toBlob(blob=>{if(blob)triggerDownload(blob,`${slugify(text("name")||"monster")}.png`);else alert("PNG не собрался в этом браузере.");URL.revokeObjectURL(url)},"image/png")};img.onerror=()=>{alert("PNG-экспорт в этой локальной версии всё ещё зависит от браузера. Если кнопка не сработала, открой проект в Chrome/Edge или выгрузи JSON и используй веб-версию после публикации.");URL.revokeObjectURL(url)};img.src=url}
function triggerDownload(blob,filename){const link=document.createElement("a");link.href=URL.createObjectURL(blob);link.download=filename;document.body.appendChild(link);link.click();setTimeout(()=>{URL.revokeObjectURL(link.href);link.remove()},700)}
function escapeHtml(str){return String(str).replaceAll("&","&amp;").replaceAll("<","&lt;").replaceAll(">","&gt;").replaceAll('"',"&quot;")}function escapeAttr(str){return escapeHtml(str)}function slugify(str){return String(str).trim().toLowerCase().replace(/[^\p{L}\p{N}]+/gu,"-").replace(/^-+|-+$/g,"")}
document.addEventListener("DOMContentLoaded",()=>{
  const imgInput=document.getElementById("imageUpload");
  if(imgInput){
    imgInput.addEventListener("change",()=>{
      const file=imgInput.files && imgInput.files[0];
      if(file && /\.(tif|tiff)$/i.test(file.name)){
        setTimeout(()=>alert("TIFF выбран. Некоторые браузеры не умеют показывать TIFF локально без отдельного декодера. Если превью не появится, лучше конвертировать файл в PNG/WebP."),50);
      }
    });
  }
});

document.addEventListener("DOMContentLoaded",()=>{
  document.querySelectorAll(".summary-tools .help-btn").forEach(btn=>{
    btn.addEventListener("click",(e)=>{e.preventDefault();e.stopPropagation();});
    btn.addEventListener("mousedown",(e)=>{e.preventDefault();e.stopPropagation();});
  });
});

document.addEventListener("click", (e) => {
  const btn = e.target.closest(".help-btn");
  if (!btn) return;
  if (btn.closest("summary")) {
    e.preventDefault();
    e.stopPropagation();
    openHelp(btn.dataset.helpTitle || "Подсказка", btn.dataset.helpText || "", btn.dataset.helpImage || "");
  }
});
document.addEventListener("mousedown", (e) => {
  const btn = e.target.closest(".help-btn");
  if (btn && btn.closest("summary")) {
    e.preventDefault();
    e.stopPropagation();
  }
});
